import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SideBar } from "./sideBar";
import { SidebarProvider } from "./SidebarContext.tsx"; // Import SidebarProvider

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SidebarProvider>
          <div className="flex h-screen">
            <div className="sticky top-0 h-full bg-gray-100"> 
              <SideBar /> 
            </div>
            <div className="flex-grow p-4 overflow-y-auto">
              {children}
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
